action: train
content_image_folder: testset_content
content_image_path: /home/zenn/StyleTransfer_test_data/testset_content_2
content_layers:
- REPLACE/last-style-layer
content_weight: 1
image_saving_path: /home/zenn/NeuralStyleTransfer/experiments/
lr: 0.001
model_dir: /home/zenn/StyleTransfer_test_data/torchvision_models
model_url: https://download.pytorch.org/models/vgg19-dcbb9e9d.pth
name: "content_image_path: /home/zenn/StyleTransfer_test_data/testset_content_2\t\
  \ lr: 0.001\t style_image_path: /home/zenn/StyleTransfer_test_data/testset_style_4\t\
  \ style_layers: ['conv_1_1', 'conv_1_2', 'conv_2_1', 'conv_2_2']\t style_weight:\
  \ 100\t"
steps: 2000000
style_image_folder: testset_style
style_image_path: /home/zenn/StyleTransfer_test_data/testset_style
style_layers:
- conv_1_1
- conv_1_2
- conv_2_1
- conv_2_2
style_weight: 100
